steps:
# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build tagged
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/qualis_static_website:$SHORT_SHA'
  - '.'

# This step builds the container image to latest
- name: 'gcr.io/cloud-builders/docker'
  id: Build latest
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/qualis_static_website:latest'
    - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push tagged
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/qualis_static_website:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/docker'
  id: Push latest
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/qualis_static_website:latest'

# This step updates our manifest with the latest image tag
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Set New Image In Manifest'
  entrypoint: /bin/sh
  args: ['-c','sed -i "s,LATEST_IMAGE_TAG,gcr.io/$PROJECT_ID/qualis_static_website:$SHORT_SHA," kubernetes/deployment.yaml']

#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  id: Applying namespace
  args: ['apply', '-f', 'kubernetes/namespace.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=personal-projects'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Applying deployment
  args: ['apply', '-f', 'kubernetes/deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=personal-projects'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Applying service
  args: ['apply', '-f', 'kubernetes/service.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=personal-projects'