apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "qualis-static-website"
  namespace: "qualis"
  labels:
    app: "qualis-static-website"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "qualis-static-website"
  template:
    metadata:
      labels:
        app: "qualis-static-website"
    spec:
      containers:
      - name: "qualis-static-website"
        image: LATEST_IMAGE_TAG
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
