apiVersion: "v1"
kind: "Service"
metadata:
  name: "qualis_static_website"
  namespace: "qualis"
  labels:
    app: "qualis_static_website"
spec:
  ports:
  - protocol: "TCP"
    port: 9011
    targetPort: 80
  selector:
    app: "qualis_static_website"
  type: "LoadBalancer"
  loadBalancerIP: ""
