apiVersion: "v1"
kind: "Service"
metadata:
  name: "qualis-static-website"
  namespace: "qualis"
  labels:
    app: "qualis-static-website"
spec:
  ports:
  - protocol: "TCP"
    port: 2000
    targetPort: 80
  selector:
    app: "qualis-static-website"
  type: "LoadBalancer"
  loadBalancerIP: ""
