name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for helping us find a new issue. I guess this is your first issue. Congratulations'
        pr-message: 'Thank you for helping us fix the issue. I guess this is your first pr'
